config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#home"
  get 'about'   => 'static_pages#about'
  get '/folders/:id', to: 'folders#show', as: 'folder'

  get '/dropbox_authorize' => 'dropbox#authorize', as: 'dropbox_authorize'
  get '/dropbox_deauthorize' => 'dropbox#deauthorize', as: 'dropbox_deauthorize'
  get '/dropbox_callback' => 'dropbox#callback', as: 'dropbox_callback'
  get '/dropbox_download/:parent_id/:id' => 'dropbox#download'
  get '/dropbox_dirty_check/:id' => 'dropbox#dirty_check'
  post '/dropbox_upload' => 'dropbox#upload'
  post '/dropbox_create_folder/:parent_id/:name' => 'dropbox#create_folder'
  delete '/dropbox_delete_item/:parent_id/:id' => 'dropbox#delete_item'
  get '/dropbox_hard_refresh' => 'dropbox#hard_refresh', as: 'dropbox_hard_refresh'

  get '/onedrive_authorize' => 'onedrive#authorize', as: 'onedrive_authorize'
  get '/onedrive_deauthorize' => 'onedrive#deauthorize', as: 'onedrive_deauthorize'
  get '/onedrive_callback' => 'onedrive#callback', as: 'onedrive_callback'
  get '/onedrive_download/:parent_id/:id' => 'onedrive#download'
  get '/onedrive_dirty_check/:id' => 'onedrive#dirty_check'
  post '/onedrive_upload/' => 'onedrive#upload'
  post '/onedrive_create_folder/:parent_id/:name' => 'onedrive#create_folder'
  delete '/onedrive_delete_item/:parent_id/:id' => 'onedrive#delete_item'
  get '/onedrive_hard_refresh' => 'onedrive#hard_refresh', as: 'onedrive_hard_refresh'

  get '/googledrive_authorize' => 'googledrive#authorize', as: 'googledrive_authorize'
  get '/googledrive_deauthorize' => 'googledrive#deauthorize', as: 'googledrive_deauthorize'
  get '/googledrive_callback' => 'googledrive#callback', as: 'googledrive_callback'
  get '/googledrive_download/:parent_id/:id' => 'googledrive#download'
  get '/googledrive_dirty_check/:id' => 'googledrive#dirty_check'
  post '/googledrive_upload/' => 'googledrive#upload'
  post '/googledrive_create_folder/:parent_id/:name' => 'googledrive#create_folder'
  delete '/googledrive_delete_item/:parent_id/:id' => 'googledrive#delete_item'
  get '/googledrive_hard_refresh' => 'googledrive#hard_refresh', as: 'googledrive_hard_refresh'

  devise_for :users
  resources :users

end

app/views/layouts/home/logged_in/_component.html.erb
<div class="<%= servicesConnected%>" id="<%= serviceContainerId %>">
    <% unless service_connected?(serviceName.capitalize) %>
        <%= react_component('FoldersContainer', {foldersPath: folder_path(serviceRootFolder), service: serviceName}) -%>

        <!-- Modal -->
        <div id= "<%="uploadFile-" + serviceName%>" class="modal fade" role="dialog">
          <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">File Upload</h4>
              </div>
              <div class="modal-body">
                  <p> Select file(s) to upload</p>
                  <p> Maximum 3 files at 100mb each</p>
                    <%= form_tag( serviceFormTagText, :multipart => true, :id => serviceFormTagId) do %>
                        <%= label_tag(:uploaded_file, 'Upload your file')
                        file_field_tag(:uploaded_file, multiple: true) %>
                    <% end %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>

          </div>
        </div>


    <% end%>
</div>

app/views/layouts/home/logged_in/_edit.html.erb
<!-- Modal -->
<div id= "edit-user" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Change Password</h4>
      </div>
      <div class="modal-body">
          <%= form_for(current_user) do |f| %>
            <div class="field">
              <%= f.label :email %><br>
              <%= f.text_field :email %>
            </div>
            <div class="field">
              <%= f.label :password %><br>
              <%= f.password_field :password %>
            </div>
            <div class="actions">
              <%= f.submit %>
            </div>
          <% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/layouts/home/logged_in/_logged_in.erb
<div class="logged-in-container">
    <div class="col-md-12">
        <div class="main-text-group">
            <h1>Welcome to Store-IT</h1>
        </div>
    </div>
    <div class="col-md-12 settings">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <div class="col-md-4 col-md-offset-2">
                <%= link_to "Edit Account", "#edit-user", :class => "my-links", "data-toggle" => "modal" %>
            </div>
            <div class="col-md-4 col-md-offset-2">
                <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "my-links" -%>
            </div>
        </div>
        <div class="col-md-4">
        </div>
    </div>
    <div class="col-md-12">
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
            <div class="connect-button-group">
                <div class="col-md-4">
                    <%= render :partial => 'layouts/home/logged_in/service_button',
                               :locals => {:serviceName => "dropbox", :serviceAuthorizePath => dropbox_authorize_path,
                               :serviceDeauthorizePath => dropbox_deauthorize_path} %>
                </div>
                <div class="col-md-4">
                    <%= render :partial => 'layouts/home/logged_in/service_button',
                               :locals => {:serviceName => "onedrive", :serviceAuthorizePath => onedrive_authorize_path,
                               :serviceDeauthorizePath => onedrive_deauthorize_path} %>
                </div>
                <div class="col-md-4">
                    <%= render :partial => 'layouts/home/logged_in/service_button',
                               :locals => {:serviceName => "googledrive", :serviceAuthorizePath => googledrive_authorize_path,
                               :serviceDeauthorizePath => googledrive_deauthorize_path} %>
                </div>
            </div>
        </div>
        <div class="col-md-3">
        </div>
    </div>
</div>

<div class="col-md-12">
    <!-- Check Services  -->
    <% servicesConnected = how_many_connected%>

    <%= render :partial => 'layouts/home/logged_in/component', :locals => { :serviceName => "dropbox",  :serviceAuthorizePath => dropbox_authorize_path,
                                                     :serviceContainerId => "dropbox-container", :serviceRootFolder => @dropbox_root,
                                                     :serviceFormTagText => "dropbox_upload", :serviceFormTagId => "dropbox-form",
                                                     :serviceDeauthorizePath => dropbox_deauthorize_path, :servicesConnected => servicesConnected}%>

    <%= render :partial => 'layouts/home/logged_in/component', :locals => { :serviceName => "onedrive", :serviceAuthorizePath => onedrive_authorize_path,
                                                     :serviceContainerId => "onedrive-container", :serviceRootFolder => @onedrive_root,
                                                     :serviceFormTagText => "onedrive_upload", :serviceFormTagId => "onedrive-form",
                                                     :serviceDeauthorizePath => onedrive_deauthorize_path, :servicesConnected => servicesConnected}%>

    <%= render :partial => 'layouts/home/logged_in/component', :locals => { :serviceName => "googledrive", :serviceAuthorizePath => googledrive_authorize_path,
                                                     :serviceContainerId => "googledrive-container", :serviceRootFolder => @googledrive_root,
                                                     :serviceFormTagText => "googledrive_upload", :serviceFormTagId => "googledrive-form",
                                                     :serviceDeauthorizePath => googledrive_deauthorize_path, :servicesConnected => servicesConnected}%>
</div>

<%= render :partial => 'layouts/home/logged_in/edit' %>

app/views/layouts/home/logged_in/_service_button.html.erb
<button type="submit" class="connect-button">
    <div class="col-md-12">
        <%= image_tag(serviceName+".png", :class => serviceName+"-logo logo" )%>
    </div>
    <% if service_connected?(serviceName.capitalize) %>
        <div class="col-md-12">
            <%= link_to "Connect " + serviceName.capitalize, serviceAuthorizePath -%>
        </div>
    <% else %>
        <div class="col-md-12">
            <%= link_to "Disconnect " + serviceName.capitalize, serviceDeauthorizePath -%>
        </div>
    <% end%>
</button>