config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#home"
  get 'about'   => 'static_pages#about'
  get '/folders/:id', to: 'folders#show', as: 'folder'

  get '/dropbox_authorize' => 'dropbox#authorize', as: 'dropbox_authorize'
  get '/dropbox_deauthorize' => 'dropbox#deauthorize', as: 'dropbox_deauthorize'
  get '/dropbox_callback' => 'dropbox#callback', as: 'dropbox_callback'
  get '/dropbox_download/:parent_id/:id' => 'dropbox#download'
  get '/dropbox_dirty_check/:id' => 'dropbox#dirty_check'
  post '/dropbox_upload' => 'dropbox#upload'
  post '/dropbox_create_folder/:parent_id/:name' => 'dropbox#create_folder'
  delete '/dropbox_delete_item/:parent_id/:id' => 'dropbox#delete_item'
  get '/dropbox_hard_refresh' => 'dropbox#hard_refresh', as: 'dropbox_hard_refresh'

  get '/onedrive_authorize' => 'onedrive#authorize', as: 'onedrive_authorize'
  get '/onedrive_deauthorize' => 'onedrive#deauthorize', as: 'onedrive_deauthorize'
  get '/onedrive_callback' => 'onedrive#callback', as: 'onedrive_callback'
  get '/onedrive_download/:parent_id/:id' => 'onedrive#download'
  get '/onedrive_dirty_check/:id' => 'onedrive#dirty_check'
  post '/onedrive_upload/' => 'onedrive#upload'
  post '/onedrive_create_folder/:parent_id/:name' => 'onedrive#create_folder'
  delete '/onedrive_delete_item/:parent_id/:id' => 'onedrive#delete_item'
  get '/onedrive_hard_refresh' => 'onedrive#hard_refresh', as: 'onedrive_hard_refresh'

  get '/googledrive_authorize' => 'googledrive#authorize', as: 'googledrive_authorize'
  get '/googledrive_deauthorize' => 'googledrive#deauthorize', as: 'googledrive_deauthorize'
  get '/googledrive_callback' => 'googledrive#callback', as: 'googledrive_callback'
  get '/googledrive_download/:parent_id/:id' => 'googledrive#download'
  get '/googledrive_dirty_check/:id' => 'googledrive#dirty_check'
  post '/googledrive_upload/' => 'googledrive#upload'
  post '/googledrive_create_folder/:parent_id/:name' => 'googledrive#create_folder'
  delete '/googledrive_delete_item/:parent_id/:id' => 'googledrive#delete_item'
  get '/googledrive_hard_refresh' => 'googledrive#hard_refresh', as: 'googledrive_hard_refresh'

  devise_for :users
  resources :users

end

app/views/layouts/home/logged_out/_logged_out.html.erb
<div class="main-container">
    <div class="welcome-text col-md-6">
        <div class="page-header">
            <h1>Welcome to Store-IT</br>
                <small>A centralized location for all of your cloud storage management needs. </small>
            </h1>
        </div>
    </div>
    <div class="login-section col-md-4 col-md-offset-1 ">
        <div class="col-md-5">
            <%= render 'layouts/home/logged_out/login' -%>
        </div>
        <div class="col-md-5 col-md-offset-2">
            <%= render 'layouts/home/logged_out/signup' -%>
        </div>
    </div>
    <div class="my-info">
        <div class="col-md-2">
        </div>
        <div class="col-md-8">
            <div class="col-md-4">
                <div class="inner-container animated slideInLeft">
                    <div class="glyphicon glyphicon-user"></div>
                    <h3> Signup </h3>
                    <p> Simply sign up to a new Store-IT account and provide an email and password to start storing today! </p>
                    <p> If you already have your account, just log in. </p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="inner-container animated slideInUp">
                    <div class="glyphicon glyphicon-refresh"></div>
                    <h3> Connect </h3>
                    <p>Connect Store-IT to one of the supported services, such as: Dropbox, One Drive and Google Drive.</p>
                    <p>Allow Store-IT access to manage user files.</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="inner-container animated slideInRight">
                    <div class="glyphicon glyphicon-cloud"></div>
                    <h3> Manage </h3>
                    <p> Store-IT allows you to create and delete folders, and upload and download files while remaining in sync with the service.  Managing storage accross multiple services has never been easier.</p>
                </div>
            </div>
        </div>
        <div class="col-md-2">
        </div>
    </div>
</div>

<%= render 'layouts/home/logged_out/password_reset' -%>

app/views/layouts/home/logged_out/_login.html.erb
<h2>Log in</h2>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| -%>
<%= devise_error_messages! -%>
  <div class="field">
    <%= f.label :email -%><br />
    <%= f.email_field :email, autofocus: true -%>
  </div>

  <div class="field">
    <%= f.label :password -%><br />
    <%= f.password_field :password, autocomplete: "off"-%>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me -%>
      <%= f.label :remember_me -%>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit "Log in", :class => "base-button"  -%>
    <button type="button" class="base-button" data-toggle="modal" data-target="#passwordReset">Reset Password</button>
  </div>

<% end %>

app/views/layouts/home/logged_out/_password_reset.html.erb
<!-- Modal -->
<div id="passwordReset" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Reset Password</h4>
      </div>
      <div class="modal-body">
          <p> Enter your email address to update your password.</p>
          <%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>
            <div class="field">
              <%= f.label :email %><br />
              <%= f.email_field :email, autofocus: true %>
            </div>
            <div class="actions">
              <%= f.submit "Submit" %>
            </div>
          <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/layouts/home/logged_out/_signup.html.erb
<h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| -%>
<%= devise_error_messages! -%>
  <div class="field">
    <%= f.label :email -%><br />
    <%= f.email_field :email, autofocus: true -%>
  </div>

  <div class="field">
    <%= f.label :password -%>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" -%>
  </div>

  <div class="field">
    <%= f.label :password_confirmation -%><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" -%>
  </div>
  </br>
  <div class="actions">
    <%= f.submit "Sign up", :class => "base-button" -%>
  </div>
<% end %>